export interface GameItem {
  id: string;
  name: string;
  description: string;
  iconName: string;
  isFunctional: boolean;
  tagline: string;
  minBet?: string;
  maxMultiplier?: string;
  gradientColors: string[];
}

export const SCATTER_GAMES: GameItem[] = [
  {
    id: 'lucky-spin',
    name: 'Lucky Spin',
    description: 'Spin the luxury wheel for instant rewards & multipliers!',
    iconName: 'aperture',
    isFunctional: true,
    tagline: 'HOT GAME',
    minBet: 'Free Spin',
    maxMultiplier: '500x',
    gradientColors: ['#0D382A', '#1A5E47'],
  },
  {
    id: 'golden-scatter',
    name: 'Golden Scatter',
    description: 'Match golden scatter symbols for mega jackpot payouts.',
    iconName: 'sparkles',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱50',
    maxMultiplier: '1000x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'fortune-coins',
    name: 'Fortune Coins',
    description: 'Flip ancient golden coins to trigger cascading multipliers.',
    iconName: 'disc',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱20',
    maxMultiplier: '250x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'emerald-rush',
    name: 'Emerald Rush',
    description: 'Enter the deep emerald vault for rapid diamond scatters.',
    iconName: 'diamond',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱100',
    maxMultiplier: '2000x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'lucky-7',
    name: 'Lucky 7',
    description: 'Classic 3-reel scatter slots with triple gold sevens.',
    iconName: 'trophy',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱10',
    maxMultiplier: '777x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'treasure-scatter',
    name: 'Treasure Scatter',
    description: 'Unearth hidden chests packed with glowing bonus coins.',
    iconName: 'gift',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱50',
    maxMultiplier: '500x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'dragon-realm',
    name: 'Dragon Realm',
    description: 'Awaken the fire dragon for explosive multiplier multipliers.',
    iconName: 'flame',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱30',
    maxMultiplier: '888x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'royal-slots',
    name: 'Royal Slots',
    description: 'Crown symbols bring VIP scatter bonuses and free spins.',
    iconName: 'ribbon',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱25',
    maxMultiplier: '600x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'wild-pharaoh',
    name: 'Wild Pharaoh',
    description: 'Ancient pyramids hide secret scatter multiplier rounds.',
    iconName: 'star',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱50',
    maxMultiplier: '1500x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'coin-frenzy',
    name: 'Coin Frenzy',
    description: 'Rapid coin drops give fast-paced instant win payouts.',
    iconName: 'cash',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱15',
    maxMultiplier: '300x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'diamond-bonanza',
    name: 'Diamond Bonanza',
    description: 'Glittering diamond scatters pay on all active paylines.',
    iconName: 'cube',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱40',
    maxMultiplier: '1200x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'super-scatter',
    name: 'Super Scatter',
    description: 'High volatility scatter action with mega jackpots.',
    iconName: 'flash',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱100',
    maxMultiplier: '5000x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'magic-wheel',
    name: 'Magic Wheel',
    description: 'Mystical wheel of fortune with instant cash prizes.',
    iconName: 'color-palette',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱20',
    maxMultiplier: '400x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'vegas-nights',
    name: 'Vegas Nights',
    description: 'Bright neon city lights bring mega scatter multipliers.',
    iconName: 'moon',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱50',
    maxMultiplier: '999x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'jackpot-city',
    name: 'Jackpot City',
    description: 'Progressive city wide jackpot rewards for high rollers.',
    iconName: 'stats-chart',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱200',
    maxMultiplier: '10000x',
    gradientColors: ['#09261C', '#103E2F'],
  },
  {
    id: 'golden-vault',
    name: 'Golden Vault',
    description: 'Unlock the high-security vault of golden scatter coins.',
    iconName: 'key',
    isFunctional: false,
    tagline: 'COMING SOON',
    minBet: '₱75',
    maxMultiplier: '2500x',
    gradientColors: ['#09261C', '#103E2F'],
  },
];
